/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;
import java.awt.*;
import java.awt.image.*;
import java.sql.*;
import java.io.*;
import javax.swing.*;
import javax.imageio.*;
/**
 *
 * @author RAVI PANCHAL
 */
public class Genrate_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Genrate_Bill
     */
    public Genrate_Bill() {
        initComponents();
        setDetail();
    }
    
    int meterno;
    String year;
    String month;
    public void setDetail()
    {//set all details in bills
        final int RATE = 10;
        final int GST_RATE = 9;
        
        meterno = PayBill.meterno;
        String fname = PayBill.fname;
        String lname = PayBill.lname;
        String district = PayBill.district;
        String city = PayBill.city;
        String mobile = PayBill.mobile;
        String pincode = PayBill.pincode;
        int unit = PayBill.unit;
        year = PayBill.year;
        month = PayBill.month;
        
        int before_gst = unit * RATE;
        int gst = (before_gst * 9) / 100;
        int after_gst = before_gst + gst;
        
        lb_year.setText(year);
        lb_month.setText(month);
        lb_meter.setText(String.valueOf(meterno));
        lb_fname.setText(fname);
        lb_lname.setText(lname);
        lb_mobile.setText(mobile);
        lb_city.setText(city);
        lb_district.setText(district);
        lb_pincode.setText(pincode);
        
        lb_unit.setText(String.valueOf(unit));
        lb_month2.setText(month);
        lb_rate.setText(String.valueOf(RATE));
        lb_bgst.setText(String.valueOf(before_gst));
        lb_gst.setText(String.valueOf(gst));
        lb_agst.setText(String.valueOf(after_gst));
        lb_total.setText(String.valueOf(after_gst));
        
        //check bill is paid or not
        try
        {
            Connection con = DBconnection.getConnection();
            String sql = "select * from paid_data where meterno=? and year=? and month=? and amt=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, meterno);
            pst.setString(2, year);
            pst.setString(3, month);
            pst.setInt(4, after_gst);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                lb_paid.setText("PAID");
            }
            else
            {
                lb_paid.setText("NOT PAY");
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void saveImage(String name,String type) 
    {
        BufferedImage image = new BufferedImage(getWidth(),getHeight(), BufferedImage.TYPE_INT_RGB);
	Graphics2D g2 = image.createGraphics();
	paint(g2);
	try
        {
            ImageIO.write(image, type, new File(name+"."+type));
	} 
        catch (Exception e) 
        {
            e.printStackTrace();
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new rojerusan.RSPanelImage();
        lb_year = new javax.swing.JLabel();
        lb_month = new javax.swing.JLabel();
        lb_meter = new javax.swing.JLabel();
        lb_fname = new javax.swing.JLabel();
        lb_lname = new javax.swing.JLabel();
        lb_mobile = new javax.swing.JLabel();
        lb_city = new javax.swing.JLabel();
        lb_district = new javax.swing.JLabel();
        lb_pincode = new javax.swing.JLabel();
        lb_unit = new javax.swing.JLabel();
        lb_month2 = new javax.swing.JLabel();
        lb_rate = new javax.swing.JLabel();
        lb_bgst = new javax.swing.JLabel();
        lb_gst = new javax.swing.JLabel();
        lb_agst = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_save = new javax.swing.JLabel();
        lb_paid = new javax.swing.JLabel();
        bt_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bill_format.png"))); // NOI18N
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_year.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_year.setForeground(new java.awt.Color(255, 255, 255));
        lb_year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 7, 50, 20));

        lb_month.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 35, 100, 30));

        lb_meter.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_meter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 75, 100, 30));

        lb_fname.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 75, 100, 30));

        lb_lname.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 75, 100, 30));

        lb_mobile.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_mobile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 30));

        lb_city.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, 30));

        lb_district.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        lb_district.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 128, 100, 30));

        lb_pincode.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_pincode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 184, 100, 30));

        lb_unit.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_unit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 275, 100, 30));

        lb_month2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_month2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 315, 100, 30));

        lb_rate.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_rate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 30));

        lb_bgst.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_bgst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_bgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 100, 30));

        lb_gst.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_gst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 100, 30));

        lb_agst.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lb_agst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_agst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 100, 30));

        lb_total.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 575, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Rs.");
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 575, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rs.");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rs.");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 30, 30));

        bt_save.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_save.setText("SAVE");
        bt_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_saveMouseClicked(evt);
            }
        });
        MainPanel.add(bt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 685, 50, 20));

        lb_paid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_paid.setForeground(new java.awt.Color(51, 204, 0));
        lb_paid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_paid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        MainPanel.add(lb_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 575, 90, 30));

        bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_closeMouseClicked(evt);
            }
        });
        MainPanel.add(bt_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(550, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_saveMouseClicked
        saveImage(String.valueOf(meterno)+"_"+year+"_"+month,"png");
        JOptionPane.showMessageDialog(this, "Image Save SuccesFully");
        this.dispose();
    }//GEN-LAST:event_bt_saveMouseClicked

    private void bt_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genrate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genrate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genrate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genrate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genrate_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSPanelImage MainPanel;
    private javax.swing.JLabel bt_close;
    private javax.swing.JLabel bt_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_agst;
    private javax.swing.JLabel lb_bgst;
    private javax.swing.JLabel lb_city;
    private javax.swing.JLabel lb_district;
    private javax.swing.JLabel lb_fname;
    private javax.swing.JLabel lb_gst;
    private javax.swing.JLabel lb_lname;
    private javax.swing.JLabel lb_meter;
    private javax.swing.JLabel lb_mobile;
    private javax.swing.JLabel lb_month;
    private javax.swing.JLabel lb_month2;
    private javax.swing.JLabel lb_paid;
    private javax.swing.JLabel lb_pincode;
    private javax.swing.JLabel lb_rate;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_unit;
    private javax.swing.JLabel lb_year;
    // End of variables declaration//GEN-END:variables
}
