/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author RAVI PANCHAL
 */
public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    public PayBill() {
        initComponents();
    }
    //get value from text field and send it to nextframe
    //thats why we store to as globle static
    static int meterno;
    static String fname;
    static String lname;
    static String district;
    static String city;
    static String mobile;
    static String pincode;
    static int unit;
    static String year;
    static String month;
    
    DefaultTableModel model;
    public void setTable()
    {
        String find_cos = txt_search.getText();
        String find_year = (String) combo_year.getSelectedItem();
        String find_month = (String) combo_month.getSelectedItem();
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));
        try
        {
            Connection con = DBconnection.getConnection();
            String sql = "select * from customer where meterno=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(find_cos));
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                String sql1 = "select * from unit_data where meterno=? and year=? and month=?";
                PreparedStatement pst1 = con.prepareStatement(sql1);
                pst1.setInt(1, Integer.parseInt(find_cos));
                pst1.setString(2, find_year);
                pst1.setString(3, find_month);
                
                ResultSet rs1 = pst1.executeQuery();
                if(rs1.next())
                {
                    meterno = rs.getInt(1);
                    fname = rs.getString(2);
                    lname = rs.getString(3);
                    district = rs.getString(4);
                    city = rs.getString(5);
                    mobile = rs.getString(6);
                    pincode = rs.getString(7);
                    unit = rs1.getInt(4);
                    year = rs1.getString(2);
                    month = rs1.getString(3);
                    
                    Object[] obj = {meterno,fname,lname,district,city,mobile,pincode,unit};
                
                    model = (DefaultTableModel) c_table.getModel();
                    model.addRow(obj);
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "There is No Data of Month "+find_month);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "There is No Customer Like This "+find_cos);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void clearTable()
    {
        model = (DefaultTableModel) c_table.getModel();
        model.setRowCount(0);
    }
    //set details into pay amount section field
    static int payAmt;
    public void setPayAmtDetail()
    {
        final int RATE = 10;
        final int GST_RATE = 9;
        int rowNo = c_table.getSelectedRow();
        model = (DefaultTableModel) c_table.getModel();
        
        txt_pay_meter.setText(model.getValueAt(rowNo,0).toString());
        txt_pay_unit.setText(model.getValueAt(rowNo,7).toString());
        
        int unit = Integer.parseInt(txt_pay_unit.getText());
        int bgst = unit * RATE;
        int gst = (bgst * GST_RATE)/100;
        payAmt = bgst + gst;
        
        txt_pay_amt.setText(String.valueOf(payAmt));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelImage = new rojerusan.RSPanelImage();
        bt_back = new rojerusan.RSButtonMetro();
        txt_meterno = new app.bolivia.swing.JCTextField();
        txt_fname = new app.bolivia.swing.JCTextField();
        txt_lname = new app.bolivia.swing.JCTextField();
        txt_district = new app.bolivia.swing.JCTextField();
        txt_city = new app.bolivia.swing.JCTextField();
        txt_mobile = new app.bolivia.swing.JCTextField();
        txt_pincode = new app.bolivia.swing.JCTextField();
        txt_unit = new app.bolivia.swing.JCTextField();
        bt_genratebill = new javax.swing.JLabel();
        bt_find = new rojerusan.RSButtonMetro();
        txt_search = new app.bolivia.swing.JCTextField();
        combo_year = new rojerusan.RSComboMetro();
        combo_month = new rojerusan.RSComboMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        c_table = new javax.swing.JTable();
        txt_pay_meter = new app.bolivia.swing.JCTextField();
        txt_pay_unit = new app.bolivia.swing.JCTextField();
        txt_pay_amt = new app.bolivia.swing.JCTextField();
        bt_pay = new javax.swing.JLabel();
        bt_clear = new rojerusan.RSButtonMetro();
        bt_checkpaid = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelImage.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Icon/PayBIll.png"))); // NOI18N
        PanelImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_back.setBackground(new java.awt.Color(255, 0, 102));
        bt_back.setText("Back");
        bt_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backMouseClicked(evt);
            }
        });
        PanelImage.add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 30));

        txt_meterno.setBackground(new java.awt.Color(8, 130, 220));
        txt_meterno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_meterno.setForeground(new java.awt.Color(255, 255, 255));
        txt_meterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_meterno.setPhColor(new java.awt.Color(255, 255, 255));
        txt_meterno.setPlaceholder("Enter Meter No.");
        PanelImage.add(txt_meterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 85, 170, 30));

        txt_fname.setBackground(new java.awt.Color(8, 130, 220));
        txt_fname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_fname.setForeground(new java.awt.Color(255, 255, 255));
        txt_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fname.setPhColor(new java.awt.Color(255, 255, 255));
        txt_fname.setPlaceholder("Enter First Name");
        PanelImage.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 145, 170, 30));

        txt_lname.setBackground(new java.awt.Color(8, 130, 220));
        txt_lname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_lname.setForeground(new java.awt.Color(255, 255, 255));
        txt_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lname.setPhColor(new java.awt.Color(255, 255, 255));
        txt_lname.setPlaceholder("Enter Last Name");
        PanelImage.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 170, 30));

        txt_district.setBackground(new java.awt.Color(8, 130, 220));
        txt_district.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_district.setForeground(new java.awt.Color(255, 255, 255));
        txt_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_district.setPhColor(new java.awt.Color(255, 255, 255));
        txt_district.setPlaceholder("Enter Your District");
        PanelImage.add(txt_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 255, 170, 30));

        txt_city.setBackground(new java.awt.Color(8, 130, 220));
        txt_city.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_city.setForeground(new java.awt.Color(255, 255, 255));
        txt_city.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_city.setPhColor(new java.awt.Color(255, 255, 255));
        txt_city.setPlaceholder("Enter Your City");
        PanelImage.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 315, 170, 30));

        txt_mobile.setBackground(new java.awt.Color(8, 130, 220));
        txt_mobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_mobile.setForeground(new java.awt.Color(255, 255, 255));
        txt_mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mobile.setPhColor(new java.awt.Color(255, 255, 255));
        txt_mobile.setPlaceholder("Enter Your Mobile Number");
        PanelImage.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 375, 170, 30));

        txt_pincode.setBackground(new java.awt.Color(8, 130, 220));
        txt_pincode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_pincode.setForeground(new java.awt.Color(255, 255, 255));
        txt_pincode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pincode.setPhColor(new java.awt.Color(255, 255, 255));
        txt_pincode.setPlaceholder("Enter Your Pin Code");
        PanelImage.add(txt_pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 170, 30));

        txt_unit.setBackground(new java.awt.Color(8, 130, 220));
        txt_unit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        txt_unit.setForeground(new java.awt.Color(255, 255, 255));
        txt_unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_unit.setPhColor(new java.awt.Color(255, 255, 255));
        txt_unit.setPlaceholder("Enter Your Unit");
        PanelImage.add(txt_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 485, 170, 30));

        bt_genratebill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_genratebill.setForeground(new java.awt.Color(255, 255, 255));
        bt_genratebill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_genratebill.setText("Genrate Bill");
        bt_genratebill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_genratebillMouseClicked(evt);
            }
        });
        PanelImage.add(bt_genratebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 585, 95, 28));

        bt_find.setText("Find");
        bt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_findActionPerformed(evt);
            }
        });
        PanelImage.add(bt_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, -1, 30));

        txt_search.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 51, 204)));
        txt_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search.setPlaceholder("Find By Meter No.");
        PanelImage.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 30));

        combo_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        PanelImage.add(combo_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 100, 30));

        combo_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "January", "February", "March", "April", "May", "June", "July", "Augest", "Octomber", "November", "December" }));
        PanelImage.add(combo_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 130, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        c_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meter No", "First Name", "Last  Name", "District", "City", "Mobile No.", "Pin Code", "Unit"
            }
        ));
        c_table.setGridColor(new java.awt.Color(255, 255, 255));
        c_table.setRowHeight(30);
        c_table.setSelectionBackground(new java.awt.Color(54, 214, 14));
        c_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(c_table);

        PanelImage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 730, 60));

        txt_pay_meter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 102)));
        txt_pay_meter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pay_meter.setPlaceholder("Enter Meter No.");
        PanelImage.add(txt_pay_meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        txt_pay_unit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 102)));
        txt_pay_unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pay_unit.setPlaceholder("Enter Unit");
        PanelImage.add(txt_pay_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 355, -1, -1));

        txt_pay_amt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 102)));
        txt_pay_amt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pay_amt.setPlaceholder("Enter Amount");
        PanelImage.add(txt_pay_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 415, -1, -1));

        bt_pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_pay.setForeground(new java.awt.Color(255, 255, 255));
        bt_pay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_pay.setText("PAY");
        bt_pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_payMouseClicked(evt);
            }
        });
        PanelImage.add(bt_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 510, 117, 38));

        bt_clear.setText("Clear");
        bt_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_clearMouseClicked(evt);
            }
        });
        PanelImage.add(bt_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 60, 30));

        bt_checkpaid.setBackground(new java.awt.Color(255, 0, 102));
        bt_checkpaid.setText("Check Paid");
        bt_checkpaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_checkpaidMouseClicked(evt);
            }
        });
        PanelImage.add(bt_checkpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 410, 90, 30));

        jLabel1.setText("Note :- If want to check the data of user who already pay for the Bill then click on Check Paid Button");
        PanelImage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 540, 20));

        MainPanel.add(PanelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_findActionPerformed
        clearTable();
        setTable();
    }//GEN-LAST:event_bt_findActionPerformed

    private void c_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_tableMouseClicked
        int rowNo = c_table.getSelectedRow();
        model = (DefaultTableModel) c_table.getModel();

        txt_meterno.setText(model.getValueAt(rowNo,0).toString());
        txt_fname.setText(model.getValueAt(rowNo,1).toString());
        txt_lname.setText(model.getValueAt(rowNo,2).toString());
        txt_district.setText(model.getValueAt(rowNo,3).toString());
        txt_city.setText(model.getValueAt(rowNo,4).toString());
        txt_mobile.setText(model.getValueAt(rowNo,5).toString());
        txt_pincode.setText(model.getValueAt(rowNo,6).toString());
        txt_unit.setText(model.getValueAt(rowNo,7).toString());
        
        setPayAmtDetail();        
    }//GEN-LAST:event_c_tableMouseClicked

    private void bt_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseClicked
       Dashboard main = new Dashboard();
       main.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bt_backMouseClicked

    private void bt_genratebillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_genratebillMouseClicked
        Genrate_Bill bill = new Genrate_Bill();       
        bill.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_bt_genratebillMouseClicked

    private void bt_payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_payMouseClicked
        Payment pay = new Payment();
        pay.setVisible(true);
    }//GEN-LAST:event_bt_payMouseClicked

    private void bt_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_clearMouseClicked
        txt_meterno.setText("");
        txt_fname.setText("");
        txt_lname.setText("");
        txt_district.setText("");
        txt_city.setText("");
        txt_mobile.setText("");
        txt_pincode.setText("");
        txt_unit.setText("");
        txt_search.setText("");
        txt_pay_meter.setText("");
        txt_pay_unit.setText("");
        txt_pay_amt.setText("");
        combo_year.setSelectedItem("SELECT");
        combo_month.setSelectedItem("SELECT");
        
    }//GEN-LAST:event_bt_clearMouseClicked

    private void bt_checkpaidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_checkpaidMouseClicked
        PayData pay = new PayData();
        pay.setVisible(true);        
    }//GEN-LAST:event_bt_checkpaidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private rojerusan.RSPanelImage PanelImage;
    private rojerusan.RSButtonMetro bt_back;
    private rojerusan.RSButtonMetro bt_checkpaid;
    private rojerusan.RSButtonMetro bt_clear;
    private rojerusan.RSButtonMetro bt_find;
    private javax.swing.JLabel bt_genratebill;
    private javax.swing.JLabel bt_pay;
    private javax.swing.JTable c_table;
    private rojerusan.RSComboMetro combo_month;
    private rojerusan.RSComboMetro combo_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private app.bolivia.swing.JCTextField txt_city;
    private app.bolivia.swing.JCTextField txt_district;
    private app.bolivia.swing.JCTextField txt_fname;
    private app.bolivia.swing.JCTextField txt_lname;
    private app.bolivia.swing.JCTextField txt_meterno;
    private app.bolivia.swing.JCTextField txt_mobile;
    private app.bolivia.swing.JCTextField txt_pay_amt;
    private app.bolivia.swing.JCTextField txt_pay_meter;
    private app.bolivia.swing.JCTextField txt_pay_unit;
    private app.bolivia.swing.JCTextField txt_pincode;
    private app.bolivia.swing.JCTextField txt_search;
    private app.bolivia.swing.JCTextField txt_unit;
    // End of variables declaration//GEN-END:variables
}
