/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVI PANCHAL
 */
public class PayData extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public PayData() {
        initComponents();        
    }
    public void checkData()
    {//check data of paid or not
        int meter = Integer.parseInt(txt_meter.getText());
        String find_year = (String) combo_year.getSelectedItem();
        String find_month = (String) combo_month.getSelectedItem();
        try
        {
            Connection con = DBconnection.getConnection();
            String sql = "select * from paid_data where meterno=? and year=? and month=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, meter);
            pst.setString(2, find_year);
            pst.setString(3, find_month);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "You already Paid a bill AMT. :- "+rs.getInt(4));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "You Did't Pay any Bill of Month "+find_month);
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_back = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        txt_meter = new app.bolivia.swing.JCTextField();
        combo_year = new rojerusan.RSComboMetro();
        combo_month = new rojerusan.RSComboMetro();
        bt_check = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_back.setBackground(new java.awt.Color(255, 0, 102));
        bt_back.setText("Back");
        bt_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backMouseClicked(evt);
            }
        });
        jPanel1.add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 60, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHECK PAID OR NOT");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 102)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 210, 30));

        txt_meter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 0)));
        txt_meter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_meter.setPlaceholder("Enter Meter No.");
        jPanel1.add(txt_meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 100, 280, 30));

        combo_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPanel1.add(combo_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 180, 280, 30));

        combo_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "January", "February", "March", "April", "May", "June", "July", "Augest", "Octomber", "November", "December" }));
        jPanel1.add(combo_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 250, 280, 30));

        bt_check.setBackground(new java.awt.Color(255, 0, 102));
        bt_check.setText("CHECK");
        bt_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_checkMouseClicked(evt);
            }
        });
        jPanel1.add(bt_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(620, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseClicked
        PayBill pay = new PayBill();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_backMouseClicked

    private void bt_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_checkMouseClicked
        checkData();
    }//GEN-LAST:event_bt_checkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro bt_back;
    private rojerusan.RSButtonMetro bt_check;
    private rojerusan.RSComboMetro combo_month;
    private rojerusan.RSComboMetro combo_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private app.bolivia.swing.JCTextField txt_meter;
    // End of variables declaration//GEN-END:variables
}
